### ISSUE TITLE
Error: failed to fetch from registry: chosen/0.0.2

### ISSUE THREAD

**Issue by rafael-ribas** [OpenBazaar/OpenBazaar-Client#1282]
Brief Description: 

```
npm install

Output:

npm ERR! Error: failed to fetch from registry: chosen/0.0.2
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/rafael/OpenBazaar-Client/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-85-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/rafael/OpenBazaar-Client
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: chosen/0.0.2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rafael/OpenBazaar-Client/npm-debug.log
npm not ok
```

And taking a look at the error part inside the `npm-debug.log`:

```
http GET https://registry.npmjs.org/valiquire/0.3.0
ERR! Error: failed to fetch from registry: chosen/0.0.2
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/rafael/OpenBazaar-Client/npm-debug.log npm
ERR! 
ERR! System Linux 3.13.0-85-generic
ERR! command "node" "/usr/bin/npm" "install"
ERR! cwd /home/rafael/OpenBazaar-Client
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: chosen/0.0.2
verbose exit [ 1, true ]
```

Operating System (OS and version): 

`Ubuntu 12.04`

**Comment by jjeffryes** [comment]
This appears to be an installation issue specific to a particular environment. We haven't been able to reproduce it.
