### ISSUE TITLE
[OSX] Can't connect to default server.

### ISSUE THREAD

**Issue by evilsocket** [OpenBazaar/OpenBazaar-Client#1695]
Brief Description: 

The app gets stucked to "Connecting to default server ..." message.

![schermata 2016-06-12 alle 15 04 35](https://cloud.githubusercontent.com/assets/86922/15991296/241b5594-30af-11e6-82e4-e757ea611e89.png)

Operating System (OS and version): 

Mac OS X 10.11.14

OpenBazaar version (shown on `About OpenBazaar` page in menu): 

1.1.6

Hardware: 

Macbook Pro Retina

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Always

Steps to reproduce:
1. Open the client

Observed Behavior:

The client is unable to connect to the default server.

Expected Behavior:

The client should automatically connect to the default server.

**Comment by evilsocket** [comment]
I [had issues starting](https://github.com/armstrtw/rzmq/issues/18) the server, I solved with:

```
 brew uninstall zeromq
 brew install zeromq405
```

Now I see this:

![schermata 2016-06-12 alle 15 27 39](https://cloud.githubusercontent.com/assets/86922/15991412/5dc8dbc4-30b2-11e6-9883-13d006e1d63f.png)

**Comment by JustinDrake** [comment]
I'm getting the same issues. Can't connect to default server.

**Comment by hoffmabc** [comment]
As a test try specifying a different OB port 

```
-p 23344
```

**Comment by evilsocket** [comment]
@hoffmabc nope, it didn't work

![schermata 2016-06-14 alle 18 12 51](https://cloud.githubusercontent.com/assets/86922/16050347/a88f1268-325b-11e6-8d03-7f6cd61f1a84.png)

**Comment by JustinDrake** [comment]
@hoffmabc Nope.

> Last login: Tue Jun 14 16:00:58 on ttys006
> Justins-MacBook-Air:duomoney justin$ cd /Applications/OpenBazaar.app/Contents/MacOS
> Justins-MacBook-Air:MacOS justin$ ./OpenBazaar -p 23344
> 2016-06-14 17:15:11.220 OpenBazaar[4472:301020] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814)
> The certificate for this server is invalid. You might be connecting to a server that is pretending to be “updates.openbazaar.org” which could put your confidential information at risk.: (null)
> Starting OpenBazaar Server
> [STR] stderr "PyInstaller Bootloader 3.x
> LOADER: executable is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: homepath is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server
> LOADER: _MEIPASS2 is NULL
> LOADER: archivename is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: pyi_arch_check_cookie failed
> LOADER: /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard contains a digital signature
> LOADER: package found skipping digital signature in /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: Extracting binaries
> "
> [STR] stderr "LOADER: Executing self as child
> LOADER: set _MEIPASS2 to /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> "
> [STR] stderr "PyInstaller Bootloader 3.x
> "
> [STR] stderr "LOADER: executable is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: homepath is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server
> LOADER: _MEIPASS2 is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: archivename is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: pyi_arch_check_cookie failed
> LOADER: /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard contains a digital signature
> LOADER: package found skipping digital signature in /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: Already in the child - running user's code.
> LOADER: Python library: /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm/.Python
> "
> [STR] stderr "LOADER: Loaded functions from Python library.
> "
> [STR] stderr "LOADER: Manipulating environment (sys.path, sys.prefix)
> "
> [STR] stderr "LOADER: sys.prefix is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: Setting runtime options
> LOADER: Initializing python
> "
> [STR] stderr "LOADER: Overriding Python's sys.path
> LOADER: Post-init sys.path is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: Setting sys.argv
> LOADER: setting sys._MEIPASS
> LOADER: importing modules from CArchive
> "
> [STR] stderr "LOADER: extracted struct
> LOADER: callfunction returned...
> "
> [STR] stderr "LOADER: extracted pyimod01_os_path
> LOADER: callfunction returned...
> "
> [STR] stderr "LOADER: extracted pyimod02_archive
> LOADER: callfunction returned...
> "
> [STR] stderr "LOADER: extracted pyimod03_importers
> "
> [STR] stderr "LOADER: callfunction returned...
> "
> [STR] stderr "LOADER: Installing PYZ archive with Python modules.
> LOADER: PYZ archive: out00-PYZ.pyz
> "
> [STR] stderr "LOADER: Running pyiboot01_bootstrap.py
> "
> [STR] stderr "LOADER: Running pyi_rth_pkgres.py
> "
> [STR] stderr "LOADER: Running pyi_rth_twisted.py
> "
> [STR] stderr "LOADER: Running openbazaard.py
> "
> [STR] stdout "________                      __________
> _____  \ ______   ____   __________   _____  _____________  _____ _______
>  /   |   \____ _/ __ \ /    |    |  _/__  \ ___   /__  \ __  \_  __ \
> /    |    \  |_> >  ___/|   |  \    |   \ / __ _/    /  / __ _/ __ |  | \/
> _______  /   **/ _**  >**_|  /___**_  /(____  /_____ (____  (____  /**|
>         \/|**|        \/     \/       \/      \/      \/     \/     \/
> 
> OpenBazaar Server v0.1 starting...
> "
> [STR] stderr "Traceback (most recent call last):
>   File "<string>", line 307, in <module>
>   File "<string>", line 231, in **init**
>   File "<string>", line 269, in start
>   File "<string>", line 193, in run
>   File "site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
> "
> [STR] stderr "  File "site-packages/twisted/internet/tcp.py", line 984, in startListening
> "
> [STR] stderr "twisted.internet.error."
> [STR] stderr "CannotListenError: Couldn't listen on 127.0.0.1:18470: [Errno 48] Address already in use.
> openbazaard returned -1
> LOADER: OK.
> LOADER: Cleaning up Python interpreter.
> "
> [STR] stderr "LOADER: Back to parent (RC: 255)
> LOADER: Doing cleanup
> "
> [STR] stderr "LOADER: Freeing archive status for /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> "
> exited with 255
> [END] stdout "________                      __________
> _____  \ ______   ____   __________   _____  _____________  _____ _______
>  /   |   \____ _/ __ \ /    |    |  _/__  \ ___   /__  \ __  \_  __ \
> /    |    \  |_> >  ___/|   |  \    |   \ / __ _/    /  / __ _/ __ |  | \/
> _______  /   **/ _**  >**_|  /___**_  /(____  /_____ (____  (____  /**|
>         \/|**|        \/     \/       \/      \/      \/     \/     \/
> 
> OpenBazaar Server v0.1 starting...
> "
> [END] stderr "PyInstaller Bootloader 3.x
> LOADER: executable is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: homepath is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server
> LOADER: _MEIPASS2 is NULL
> LOADER: archivename is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: pyi_arch_check_cookie failed
> LOADER: /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard contains a digital signature
> LOADER: package found skipping digital signature in /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: Extracting binaries
> LOADER: Executing self as child
> LOADER: set _MEIPASS2 to /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> PyInstaller Bootloader 3.x
> LOADER: executable is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: homepath is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server
> LOADER: _MEIPASS2 is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: archivename is /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: pyi_arch_check_cookie failed
> LOADER: /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard contains a digital signature
> LOADER: package found skipping digital signature in /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> LOADER: Already in the child - running user's code.
> LOADER: Python library: /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm/.Python
> LOADER: Loaded functions from Python library.
> LOADER: Manipulating environment (sys.path, sys.prefix)
> LOADER: sys.prefix is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: Setting runtime options
> LOADER: Initializing python
> LOADER: Overriding Python's sys.path
> LOADER: Post-init sys.path is /var/folders/71/s1z0k0_j3qs6gz4zr_tt72fr0000gn/T/_MEIw1ZCZm
> LOADER: Setting sys.argv
> LOADER: setting sys._MEIPASS
> LOADER: importing modules from CArchive
> LOADER: extracted struct
> LOADER: callfunction returned...
> LOADER: extracted pyimod01_os_path
> LOADER: callfunction returned...
> LOADER: extracted pyimod02_archive
> LOADER: callfunction returned...
> LOADER: extracted pyimod03_importers
> LOADER: callfunction returned...
> LOADER: Installing PYZ archive with Python modules.
> LOADER: PYZ archive: out00-PYZ.pyz
> LOADER: Running pyiboot01_bootstrap.py
> LOADER: Running pyi_rth_pkgres.py
> LOADER: Running pyi_rth_twisted.py
> LOADER: Running openbazaard.py
> Traceback (most recent call last):
>   File "<string>", line 307, in <module>
>   File "<string>", line 231, in __init__
>   File "<string>", line 269, in start
>   File "<string>", line 193, in run
>   File "site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
>   File "site-packages/twisted/internet/tcp.py", line 984, in startListening
> twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:18470: [Errno 48] Address already in use.
> openbazaard returned -1
> LOADER: OK.
> LOADER: Cleaning up Python interpreter.
> LOADER: Back to parent (RC: 255)
> LOADER: Doing cleanup
> LOADER: Freeing archive status for /Applications/OpenBazaar.app/Contents/Resources/OpenBazaar-Server/openbazaard
> "

**Comment by evilsocket** [comment]
@JustinDrake our errors are different, you have something else listening on port 18470 ( while I dont ):

```
 twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:18470: [Errno 48] Address already in use.
```

You can try this command to see what's listening on that port:

```
sudo lsof -n -i:18470
```

**Comment by JustinDrake** [comment]
You're right. It seems I had a zombie OpenBazaar server running. I killed it and it now works :)

> Justins-MacBook-Air:duomoney justin$ sudo lsof -n -i:18470
> COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> openbazaa 787 justin   12u  IPv4 0x578e36cbc5cf5b97      0t0  TCP 127.0.0.1:18470 (LISTEN)

**Comment by evilsocket** [comment]
Glad that at least it works for you :)

**Comment by JustinDrake** [comment]
Hey @evilsocket, are you on the OpenBazaar Slack by any chance?

**Comment by evilsocket** [comment]
nope

**Comment by JustinDrake** [comment]
@evilsocket I'm personally working on Duo Search (www.duosear.ch), an OpenBazaar search engine. Hit me up if it sparks any interest whatsoever. :)

**Comment by evilsocket** [comment]
@JustinDrake nice, is it open?

**Comment by JustinDrake** [comment]
@evilsocket: Not yet. We'll probably open the frontend soon, and maybe the crawlers and scrapers at some point.

**Comment by evilsocket** [comment]
@JustinDrake well, if it's not 100% open I'm not interested :)

**Comment by JustinDrake** [comment]
@evilsocket Haha, OK :) I'll keep that in mind.

**Comment by hoffmabc** [comment]
That error you're getting @JustinDrake could be the STUN server acting up. I noticed it for a bit and then it finally went away. I think there are some tweaks to the STUN handling that could make this more rresilient.
