### ISSUE TITLE
Cannot release funds

### ISSUE THREAD

**Issue by ulrichard** [OpenBazaar/OpenBazaar-Client#1717]
Brief Description: 
When I started the order, I closed the payment window before the payment was detected. So the status dind't automatically switch to "paid".
The seller saw the transaction, and sent the item.
Now I wanted to confirm the receipt and release the funds.
So I click "Bestellung abschliessen" and enter some text. Then I press "speichern", but nothing happens.

Operating System (OS and version):  Trisquel Belenos
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.5
Hardware: Lenovo X60 libreboot

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
always for this trade, never happened with other trades.

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):
Order #68f793c9e45a4b77065136eaf56461fd9f98eb71

**Comment by jjeffryes** [comment]
When you say you click save and nothing happens, what, specifically, is nothing?

Does the save button change color at all? It should briefly become dark. 

Does the screen change? The complete order form should disappear. Does it remain on the screen?

Does an error message appear?

**Comment by ulrichard** [comment]
Yes, the save button gets darker for a second, but the screen does not change. It remains on the screen with the ratings. 
No error message on the client.
But on the server I saw this:

  File "api/restapi.py", line 55, in _authenticate
  File "api/restapi.py", line 821, in complete_order
  File "market/contracts.py", line 619, in add_receipt
  File "json/__init__.py", line 338, in loads
  File "json/decoder.py", line 366, in decode
exceptions.TypeError: expected string or buffer
2016-06-23 08:01:57+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "site-packages/twisted/web/http.py", line 1439, in dataReceived
          File "site-packages/twisted/web/http.py", line 1704, in _finishRequestBody
          File "site-packages/twisted/web/http.py", line 1767, in allContentReceived
          File "site-packages/twisted/web/http.py", line 768, in requestReceived
--- exception caught here ---
          File "site-packages/twisted/web/server.py", line 178, in process
          File "site-packages/twisted/web/server.py", line 739, in getResourceFor
          File "site-packages/twisted/web/resource.py", line 98, in getChildForRequest
          File "site-packages/twisted/web/resource.py", line 201, in getChildWithDefault
          File "site-packages/txrestapi/resource.py", line 63, in getChild
          File "site-packages/txrestapi/resource.py", line 19, in inner
          File "api/restapi.py", line 55, in _authenticate
          File "api/restapi.py", line 821, in complete_order
          File "market/contracts.py", line 619, in add_receipt
          File "json/__init__.py", line 338, in loads
          File "json/decoder.py", line 366, in decode

**Comment by ulrichard** [comment]
By looking closer, there is already an error when I load the order details:

2016-06-23 08:25:48+0200 [-] [INFO] Switching to tcp://libbitcoin3.openbazaar.org:9091
2016-06-23 08:25:48+0200 [-] [ERROR] Libbitcoin server timed out. Refreshing socket and resending requests.
Unhandled Error
Traceback (most recent call last):
  File "<string>", line 270, in start
  File "<string>", line 202, in run
  File "site-packages/twisted/internet/base.py", line 1194, in run
  File "site-packages/twisted/internet/base.py", line 1203, in mainLoop
--- exception caught here ---
  File "site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
  File "site-packages/obelisk/client.py", line 103, in _reconnect
  File "site-packages/obelisk/zmqbase.py", line 95, in _reconnect
  File "site-packages/obelisk/zmq_fallback.py", line 54, in close
  File "site-packages/twisted/internet/task.py", line 202, in stop
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.
2016-06-23 08:25:48+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "<string>", line 270, in start
          File "<string>", line 202, in run
          File "site-packages/twisted/internet/base.py", line 1194, in run
          File "site-packages/twisted/internet/base.py", line 1203, in mainLoop
        --- exception caught here ---
          File "site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
          File "site-packages/obelisk/client.py", line 103, in _reconnect
          File "site-packages/obelisk/zmqbase.py", line 95, in _reconnect
          File "site-packages/obelisk/zmq_fallback.py", line 54, in close
          File "site-packages/twisted/internet/task.py", line 202, in stop
        exceptions.AssertionError: Tried to stop a LoopingCall that was not running.

**Comment by jjeffryes** [comment]
@cpacia would the errors above stop the complete call from going through?

**Comment by ulrichard** [comment]
The problem persists with v1.1.7

**Comment by jjeffryes** [comment]
Paging @cpacia

**Comment by ulrichard** [comment]
After waiting for some time, I opened a dispute so that the seller could get his money. 
The seller can see the dispute, but apparently the moderator can't.
If I click the "Resend Start of Dispute" button, I just see the window flicker for a moment, and them my message disappears.
What can we do to release the funds?

**Comment by jjeffryes** [comment]
It sounds like the moderator isn't getting the dispute message. If the seller can see it, that means it went out correctly, and the issue may be on the moderator's node. 

Have they tried the simple things, like restarting their node?

**Comment by jjeffryes** [comment]
@ulrichard did you resolve the issue with the funds not being released?

**Comment by ulrichard** [comment]
No, the funds are still in limbo. 

The moderator said : The transaction is missing the vendor_order_confirmation section.
