### ISSUE TITLE
Error installing client: ENOENT: no such file or directory, open '/OpenBazaar-Client/.git/hooks/pre-commit'

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Client#1734]
I have been installing the client on OSX for quite a while by pulling from the git repo, npm install, and then npm start. The last time I tried this, though, I got the following error:

```
% git pull
Already up-to-date.
% npm install
> git-validate@2.1.4 install /Users/lunokhod/OpenBazaar/OpenBazaar-Client/node_modules/git-validate
> node bin/install

fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/lunokhod/OpenBazaar/OpenBazaar-Client/.git/hooks/pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.writeFileSync (fs.js:1327:33)
    at Object.exports.installHooks (/Users/lunokhod/OpenBazaar/OpenBazaar-Client/node_modules/git-validate/lib/utils.js:248:12)
    at Object.<anonymous> (/Users/lunokhod/OpenBazaar/OpenBazaar-Client/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

commit 7381c7598c4005524f197665a4ec00f14f5d4fce

**Comment by lunokhod** [comment]
I just deleted the entire repo and re-cloned it and it works fine. Not sure what the problem was...
