### ISSUE TITLE
I'm on a new IP and my client no longer connects to my server (it stays stuck on the loading screen with no way to change my server settings)

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#929]
![Uploading Screen Shot 2016-03-02 at 12.12.05 PM.png…]()

**Comment by hoffmabc** [comment]
ooh that's a good screenshot

**Comment by jjeffryes** [comment]
What do you mean by new IP? Is your server local, or remote?

**Comment by rmisio** [comment]
@morebrownies If you are trying to connect to a remote server, there is a known issue where you need to start the client _after_ guid generation is complete.

I just created a server ticket for this. For security reasons, the server was updated to stop sending certain information to the client during guid gen on remote servers. However, the way it's done, the client really has no idea what's going on. I think there's a way it can be done that would satisfy the security concerns, while allowing a reasonable client experience:

https://github.com/OpenBazaar/OpenBazaar-Server/issues/261

**Comment by morebrownies** [comment]
I'm running into this issue again. I created a new server on Digital Ocean and tried to connect to it from my local client. In my client terminal I see:

**Could not get code signature for running application**

And all I see is a spinner in the client that never goes away. I tried restarting my client a few times and I run into the same issue.

<img width="1280" alt="screenshot 2016-03-08 11 43 24" src="https://cloud.githubusercontent.com/assets/13066886/13610411/33906e74-e523-11e5-86d8-29f5d9f0f34c.png">

**Comment by rmisio** [comment]
@morebrownies this is a know issue on new remote servers. You need to wait until the server has completed the GUID gen process and then connect with the client (or re-start the client).

Once again, there is an open server issue to account for this:
OpenBazaar/OpenBazaar-Server#261

**Comment by morebrownies** [comment]
Yes it was finished generating the GUID.

**Comment by rmisio** [comment]
and still, even now if you re-start the client and try to connect to the same server, you can't connect?

Can you post the server logs?

**Comment by morebrownies** [comment]
OpenBazaar Server v0.1 starting...
Exception : No UPnP device discovered
2016-03-08 12:58:14-0500 [OpenBazaard] [INFO] Finding NAT Type...
2016-03-08 12:58:14-0500 [OpenBazaard] [INFO] Full Cone on 159.203.250.228:28467
2016-03-08 12:58:14-0500 [OpenBazaard] [INFO] Startup took 4.39 seconds
2016-03-08 12:58:15-0500 [-] [INFO] Libbitcoin server online
2016-03-08 12:58:15-0500 [Server] [INFO] bootstrapping with 2 addresses, finding neighbors...
2016-03-08 12:58:15-0500 [-] Unhandled Error
    Traceback (most recent call last):
      File "openbazaard.py", line 247, in start
        int(args.heartbeatport), time.time())
      File "openbazaard.py", line 182, in run
        reactor.run()
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/home/mbw/OpenBazaar-Server/market/network.py", line 1095, in update_listings
        l.ParseFromString(self.db.listings.get_proto())
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
        self.MergeFromString(serialized)
      File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1089, in MergeFromString
        length = len(serialized)
    exceptions.TypeError: object of type 'NoneType' has no len()

Unhandled Error
Traceback (most recent call last):
  File "openbazaard.py", line 247, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 182, in run
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "/home/mbw/OpenBazaar-Server/market/network.py", line 1095, in update_listings
    l.ParseFromString(self.db.listings.get_proto())
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1089, in MergeFromString
    length = len(serialized)
exceptions.TypeError: object of type 'NoneType' has no len()
2016-03-08 12:58:18-0500 [ConnHandler] [INFO] connected to 103.255.6.80:15601
2016-03-08 12:58:20-0500 [OpenBazaard] [INFO] bootstrap complete
2016-03-08 12:58:25-0500 [ConnHandler] [INFO] connection with 103.255.6.80:15601 terminated

**Comment by rmisio** [comment]
@cpacia Any idea why Mike is having problems connecting? I thought it was the issue with being unable to connect to a remote server during GUID gen, but it appears that the GUID gen process was already completed.

**Comment by morebrownies** [comment]
I restarted my server and it worked. Not sure why that fixed it, but I think I'm good now. We may want to keep an eye on this to see if it pops up more often.
