### ISSUE TITLE
OSX install of 1.0.6.dmg hangs with Javascript Uncaught Exception

### ISSUE THREAD

**Issue by seandotau** [OpenBazaar/OpenBazaar-Client#936]
Brief Description: Tried to install OpenBazaar-1.0.6.dmg. Hangs at the personal keys and OpenBazaar screen.

Operating System (OS and version): OSX 10.11.2
OpenBazaar version (shown on `About OpenBazaar` page in menu): OpenBazaar-1.0.6.dmg
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. Double click on OpenBazaar-1.0.6.dmg 
2. 
3. 

Observed Behavior:
Reaches "Hang tight for a few ....
Your personal keys and OpenBazaar ID are generating and should only take about 30 seconds to finish.  You'll be automatically connected to the network once the process is finished, so please hang tight.

Looking for something to do in the meantime? Read the OpenBazaar blog.

Expected Behavior:

Additional info (links, images, etc go here):
<img width="802" alt="screen shot 2016-03-03 at 12 46 49 pm" src="https://cloud.githubusercontent.com/assets/12471846/13479973/9337251c-e13f-11e5-85d8-d673191e36a3.png">

Output from View Debug Log:

Uncaught Exception:
Error: ENOENT: no such file or directory, open '../OpenBazaar-Server/ob.cfg'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync](ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at find_debug_log (/Applications/OpenBazaar.app/Contents/Resources/app/main.js:290:31)
    at menu.buildFromTemplate.click (/Applications/OpenBazaar.app/Contents/Resources/app/main.js:278:7)
    at MenuItem.click (/Applications/OpenBazaar.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:69:18)
    at Function.delegate.executeCommand (/Applications/OpenBazaar.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:128:69)

**Comment by seandotau** [comment]
Upgraded to 1.0.7 and tried again with success.
